### ISSUE TITLE
Please add support for RK312X (0x310d)

### ISSUE THREAD

**Issue by MyXelf** [neo-technologies/rkflashtool#5]
The title is pretty self-explanatory. This could be added to the pidtab structure in rkflashtool.c

I already added it in my local repo and it worked fine with some unbranded Chinese tablet

HTH

Thanks in advance

MyXelf

EDIT: Looks like it would be more appropiate to add it as RK312X for both RK3126 and RK3128

**Comment by julienchauveau** [comment]
Done. Thanks for your comment!

It seems that `0x310d` is only for RK3126 devices (yet!).
