### ISSUE TITLE
Need help to flash arnova 101 G4

### ISSUE THREAD

**Issue by nmocruz** [neo-technologies/rkflashtool#6]
Hi

I'm trying to find a way to bring a device to live. After an update my device is not booting, the screen is on, but no picture, I'm able to connect to shell in recovery but, the fastboot seems not working, the device is not recognized, I also tried ubuntu and nothing.

So I'm wondering if this can be used to flash my device in recovery mode. A sample who to make partitions and flash with this.

**Comment by ildar** [comment]
Hi!
If you managed to enter shell in recovery, then you don't need flashers.
Unfortunately shell without a picture points to the hardware problem with
display. Try disassembling and check the display cable. Anyway reflashing
wont help in this case.
Fastboot doesn't work, that's normal.

**Comment by nmocruz** [comment]
I Find out my problem. I was able to flashed it with the update_tool, but the problem was the Arnova 101 G4 firmware provided in the website. After read [this](https://forum.xda-developers.com/showthread.php?t=2683596) I figure out that the problem was caused by the firmware and a solution was flash it with a similiat table update the archos 101 cobalt.
